version: "3.8"
services:
  nginx:
    image: nginx:stable
    container_name: devfecta-nginx
    restart: unless-stopped
    ports:
      - "80:8080"
      #- "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html
    #deploy:
    #  replicas: 2
    #  update_config:
    #    parallelism: 2
    #    delay: 10s
    #  restart_policy:
    #    condition: on-failure

  # DevFecta-NGINX:
  #   image: nginx:stable
  #   container_name: DevFecta-NGINX
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./build:/usr/share/nginx/html/devfecta
  #   environment:
  #     - VIRTUAL_HOST=com.localhost
  #     - VIRTUAL_PORT=80
  #     #- LETSENCRYPT_HOST=your-website-one.com 
  #     #- LETSENCRYPT_EMAIL=your.email@domain.com
  #   #deploy:
  #   #  replicas: 2
  #   #  update_config:
  #   #    parallelism: 2
  #   #    delay: 10s
  #   #  restart_policy:
  #   #    condition: on-failure
  #   expose:
  #     - 80

  # test-NGINX:
  #   image: nginx:stable
  #   container_name: test-NGINX
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./test:/usr/share/nginx/html/test
  #   environment:
  #     - VIRTUAL_HOST=net.localhost
  #     - VIRTUAL_PORT=80
  #     - LETSENCRYPT_HOST=your-website-one.com 
  #     - LETSENCRYPT_EMAIL=your.email@domain.com
  #   #deploy:
  #   #  replicas: 2
  #   #  update_config:
  #   #    parallelism: 2
  #   #    delay: 10s
  #   #  restart_policy:
  #   #    condition: on-failure
  #   expose:
  #     - 80
    

# networks:
#   default:
#     external:
#       name: nginx-proxy

#volumes:
#  devfecta-react-php:
#  devfecta-mysql: